version: "3"
services:
  # this container will run Cypress test using built-in Electron browser
  e2e-electron:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cypress
    image: mable-web-cypress
    command: "npx cypress run"
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.json:/app/cypress.json